### ISSUE TITLE
Einarbeitung PageRank mit Python

### ISSUE THREAD

**Issue by glutengo** [Sentiments-of-Bundestag/graphenauswertung#2]
Lernziel: PageRank verstehen, grobe Idee, wie eine Implementierung in unserem Setup (Python / Flask / Neo4J) aussehen kann.

Ressourcen:
https://de.wikipedia.org/wiki/PageRank
https://neo4j.com/blog/graph-algorithms-neo4j-pagerank/

**Comment by glutengo** [comment]
@MariamaB @miiyuutou

**Comment by MariamaB** [comment]
Was wir von Gruppe 4 brauchen:
 :Abgeordneter (Node)
Id
Name
Partei
etc.
 [:PROCOMMENT] →  (Relationship)
 [:CONCOMMENT] → (Relationship)


Was wir von Gruppe 5 brauchen:
 :Fraktion bzw. Partei (Node)
Id
Name
etc.
 [:PROCOMMENT] →  (Relationship)
 [:CONCOMMENT] → (Relationship)
