### ISSUE TITLE
NaN value in sentiments

### ISSUE THREAD

**Issue by steven-mi** [Sentiments-of-Bundestag/graphenauswertung#31]
Could this be fixed? ATM we have a own solution for handling NaN values but it is not optimal. In the best case NaN value should be handled by the algorithm itself because the frontend doesn't know the meaning of NaN (negative, positive, neutral).

Endpoints:  
- `faction/graph`
- `persons/graph` (did not occur jet, but should be handled anyway)

**Comment by glutengo** [comment]
fixed in #30
